services:
  db:
    image: postgres:16.1-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"

  api:
    build: .
    expose:
      - "3000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: ./bin/rails server -b 0.0.0.0
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"

volumes:
  db_data: {}
  bundle_cache: {}
