default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>

development:
  <<: *default
  database: yapperbuilder_development

test:
  <<: *default
  database: yapperbuilder_test

production:
  primary: &primary_production
    <<: *default
    database: yapperbuilder_production
    username: yapperbuilder
    password: <%= ENV["YAPPERBUILDER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: yapperbuilder_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: yapperbuilder_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: yapperbuilder_production_cable
    migrations_paths: db/cable_migrate
